{% set name = "pyiem" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e31eed22c7a72a179e319d81bede59e6231ca58f1ffcde573a01deb099f75d57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - affine
    - defusedxml
    - docutils
    - geopandas
    - httpx
    - jinja2
    - matplotlib-base
    - metar
    - metpy
    - netCDF4
    - nh3
    - numpy
    - pandas
    - paste
    - pillow
    - pyarrow
    - pydantic
    - pygrib
    - pymemcache
    - pyogrio
    - pyproj
    - psycopg
    - rasterio
    - rasterstats
    - scipy
    - shapely
    - sqlalchemy
    - twython
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyiem

about:
  home: https://github.com/akrherz/pyIEM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A general library supporting NWS Products and the IEM Project.
  description: |
    pyIEM contains a wide collection of codes relevant for working with
    US National Weather Service data and code that supports the Iowa
    Environmental Mesonet project at Iowa State University.
  dev_url: https://github.com/akrherz/pyIEM

extra:
  recipe-maintainers:
    - akrherz
