schema_version: 1

context:
  name: pyiem
  version: "1.28.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4f3407a37355e4a08a8896e52cf50dc8b2bd3e4358bf98b68db6513714fc51e1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python >=${{ python_min }}
    - affine
    - defusedxml
    - docutils
    - geopandas >=1.2
    - jinja2
    - matplotlib-base
    - metar
    - metpy
    - netCDF4
    - numpy
    - pandas
    - paste
    - pillow
    - pyarrow
    - pydantic
    - pygrib
    - pymemcache
    - pyogrio
    - pyproj
    - psycopg
    - rasterio
    - rasterstats
    - requests
    - scipy
    - shapely
    - sqlalchemy
    - twython
    - xarray

tests:
  - python:
      imports:
        - pyiem
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: A general library supporting NWS Products and the IEM Project.
  description: |
    pyIEM contains a wide collection of codes relevant for working with
    US National Weather Service data and code that supports the Iowa
    Environmental Mesonet project at Iowa State University.
  homepage: https://github.com/akrherz/pyIEM
  repository: https://github.com/akrherz/pyIEM

extra:
  recipe-maintainers:
    - akrherz
